### ISSUE TITLE
add cleanup script?

### ISSUE THREAD

**Issue by vTNT** [Shinzu/kubernetes-consul-vault#1]

**Comment by vTNT** [comment]
such as https://github.com/kelseyhightower/consul-on-kubernetes/blob/master/cleanup

**Comment by vTNT** [comment]
when i run this command: kubectl apply volumes/storage_class.yaml
it show me some error that
error: Unexpected args: [volumes/storage_class.yaml]
See 'kubectl apply -h' for help and examples.

**Comment by vTNT** [comment]
the true command is kubectl apply -f volumes/storage_class.yaml or kubectl create -f volumes/storage_class.yaml

**Comment by vTNT** [comment]
when i run this command: kubectl describe statefulset consul;
it show that
Replicas: 3 desired | 0 total
Pods Status: 0 Running / 0 Waiting / 0 Succeeded / 0 Failed;
it didn't create any pods, so how can i solve this problem

**Comment by Shinzu** [comment]
sry saw this comment just now, did you solve your problem?

**Comment by vTNT** [comment]
yes thank you for you comment
